# generated by configure / remove this line to disable regeneration
prefix="/programs"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/taco/luatex-dev/luatex/src/libs/zziplib/zzip/.libs"
datadir="${prefix}/share"
sysconfdir="${sbindir}"
includedir="/home/taco/luatex-dev/luatex/src/libs/zziplib/."
package="zziplib"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "zziplib"
;; --help) pkg-config --help ; echo Buildscript Of "ZZipLib - libZ-based ZIP-access Library"
;; --modversion|--version) echo "0.13.47"
;; --requires) echo pkg-config zzip-zlib-config "zzip-zlib-config"
;; --libs) echo -L${libdir} "" "-lzzip"
       pkg-config zzip-zlib-config
;; --cflags) echo -I${includedir} ""
       pkg-config zzip-zlib-config
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
