#!/bin/sh
a=$1
shift
cd /opt/tex/luatex/tags
if  test -d $a ; then
  find $a -name \*~ -exec rm \{\} \;
  rm -rf $a/build $a/build-windows
  (cd $a/source ; ./texk/web2c/luatexdir/getluatexsvnversion.sh )
  ln -s $a luatex-$a
  tar cvj --exclude=.svn -f ../../luatex-$a-doc.tar.bz2 luatex-$a/manual/
  tar cvj --exclude=.svn --exclude=luatex-$a/manual -f ../../luatex-$a-source.tar.bz2 luatex-$a/*
  cd luatex-$a
  ./build.sh --mingw "$@"
  zip -j ../../../luatex-$a-win32-mingw.zip build-windows/texk/web2c/luatex.exe
  cd ..
  rm -rf $a/build-windows
  rm luatex-$a
fi
