#!/bin/sh
a=$1
shift
cd /opt/tex/luatex/tags
if  test -d $a ; then
  find $a -name \*~ -exec rm \{\} \;
  rm -rf $a/build $a/build-windows
  cd $a && source/texk/web2c/luatexdir/getluatexsvnversion.sh tags/$a && cd ..
  ln -s $a luatex-$a
  tar cvj --exclude=.svn -f ../../luatex-$a.tar.bz2 luatex-$a/*
  cd luatex-$a
  ./build.sh "$@"
  ./build.sh --mingw "$@"
  zip -j ../../../luatex-$a-win32-mingw.zip build-windows/texk/web2c/luatex.exe
  cd build/texk/web2c
  tar cjvf ../../../../../../luatex-$a-linux2.6-i386.tar.bz2 luatex
  cd ../../../..
  rm -rf $a/build $a/build-windows
  rm luatex-$a
fi
